server.port: 8089

api:
  finnhub:
    token: 'ck46ck1r01qus81pqgegck46ck1r01qus81pqgf0'
    domain: 'finnhub.io'
    base-url: 'api/v1'
    endpoints:
      stock:
        profile2: '/stock/profile2'
        quote: '/quote'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exercise4
    username: 'root'
    password: 'admin1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.jpa:
  show-sql: true
  properties: # optional to under "properties"
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      # Either to use hibernate or spring.sql.init, otherwise it duplicated to create tables
      ddl-auto: update # create, create-drop, update, none, validate
      show-sql: true
      driver-class-name: com.mysql.cj.jdbc.Driver
    sql:
      init:
       schema-locations: 

      mode: always # always
    show-sql: true
    hibernate.ddl-auto: create-drop # for development purpose